-- Add more temples with real data and enhanced features
INSERT INTO temples (name, primary_deity, tradition, description, history, location, visiting_hours, contact_info, darshan_schedule, facilities, entrance_fee, image_urls, rating, verified, booking_enabled, live_darshan_url, youtube_channel_id)
VALUES 
-- 1. Badrinath Temple
('Badrinath Temple', 'Lord Badrinath (Vishnu)', 'Vaishnavism', 
'One of the Char Dham pilgrimage sites, located in the Garhwal Himalayas. This ancient temple is dedicated to Lord Vishnu in his Badrinath form and is considered one of the most sacred Hindu temples.', 
'The temple was established by Adi Shankaracharya in the 9th century. According to legend, Lord Vishnu meditated here under a Badri tree, where Goddess Lakshmi protected him from harsh weather. The temple opens only for six months due to extreme winter conditions.', 
'{"country": "India", "state": "Uttarakhand", "city": "Badrinath", "address": "Badrinath, Chamoli District", "pincode": "246422", "lat": 30.7433, "lng": 79.4938}',
'{"summer": "4:30 AM - 1:00 PM, 4:00 PM - 9:00 PM", "winter": "Closed (Nov-Apr)", "open_period": "April to November"}',
'{"phone": "+91-1381-222411", "email": "badrinath@templetrust.org", "website": "https://badrinath-kedarnath.gov.in"}',
'[{"time": "4:30 AM", "type": "Abhishek Puja"}, {"time": "9:00 AM", "type": "Mahapuja"}, {"time": "12:00 PM", "type": "Bhog Aarti"}, {"time": "7:00 PM", "type": "Sandhya Aarti"}]',
'["Prasad Counter", "Accommodation", "Medical Facility", "Hot Water Springs", "Cloakroom", "Wheelchair Access", "Tourist Information Center", "Free WiFi"]',
'{"indian": "Free", "camera": "50 INR", "vip_darshan": "300 INR"}',
'["https://images.unsplash.com/photo-1548013146-72479768bada?w=800", "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800"]',
4.8, true, true, 'https://www.youtube.com/watch?v=badrinath_live', 'UCBadrinathTemple'),

-- 2. Kedarnath Temple
('Kedarnath Temple', 'Lord Shiva', 'Shaivism',
'One of the twelve Jyotirlingas and part of Char Dham, located in the Himalayas at an altitude of 3,583 meters. This ancient temple survived the devastating 2013 floods.',
'Built by the Pandavas and revived by Adi Shankaracharachi in the 8th century. The temple is believed to be more than 1,000 years old. It is said that the Pandavas sought Lord Shiva here to seek forgiveness after the Kurukshetra war.',
'{"country": "India", "state": "Uttarakhand", "city": "Kedarnath", "address": "Kedarnath, Rudraprayag District", "pincode": "246445", "lat": 30.7352, "lng": 79.0669}',
'{"summer": "4:00 AM - 9:00 PM", "winter": "Closed (Nov-Apr)", "open_period": "May to November"}',
'{"phone": "+91-1364-267006", "email": "kedarnath@templetrust.org", "website": "https://badrinath-kedarnath.gov.in"}',
'[{"time": "4:00 AM", "type": "Morning Aarti"}, {"time": "7:00 PM", "type": "Evening Aarti"}]',
'["Medical Camps", "Helicopter Service", "Pony Service", "Accommodation", "Blanket Facility", "Oxygen Support", "Emergency Services"]',
'{"indian": "Free", "camera": "50 INR", "helicopter": "7500 INR"}',
'["https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800"]',
4.9, true, false, null, 'UCKedarnathTemple'),

-- 3. Khajuraho Temples
('Khajuraho Group of Monuments', 'Various Deities', 'Hindu & Jain',
'UNESCO World Heritage Site famous for its stunning architecture and intricate sculptures. These temples are renowned for their nagara-style architectural symbolism and erotic sculptures.',
'Built by the Chandela dynasty between 950 and 1050 CE. Originally there were 85 temples spread over 20 square kilometers. Today, only about 25 temples remain, divided into Western, Eastern, and Southern groups.',
'{"country": "India", "state": "Madhya Pradesh", "city": "Khajuraho", "address": "Khajuraho, Chhatarpur District", "pincode": "471606", "lat": 24.8318, "lng": 79.9199}',
'{"daily": "Sunrise to Sunset", "light_show": "7:00 PM (Hindi), 8:30 PM (English)"}',
'{"phone": "+91-7686-272051", "email": "khajuraho@asi.org", "website": "https://khajuraho.nic.in"}',
'[{"time": "6:00 AM", "type": "Temple Opens"}, {"time": "7:00 PM", "type": "Light & Sound Show"}]',
'["Audio Guide", "Museum", "Handicraft Shop", "Restaurant", "Parking", "Guide Service", "Photography Allowed", "Light & Sound Show"]',
'{"indian": "40 INR", "foreigner": "600 INR", "camera": "25 INR", "video": "25 INR"}',
'["https://images.unsplash.com/photo-1586879071243-e5d9b9c62817?w=800"]',
4.7, true, false, null, null),

-- 4. Jagannath Temple, Puri
('Jagannath Temple', 'Lord Jagannath (Krishna)', 'Vaishnavism',
'One of the Char Dham pilgrimage sites, famous for the annual Rath Yatra festival. The temple is dedicated to Lord Jagannath, a form of Vishnu.',
'Built in the 12th century by King Anantavarman Chodaganga. The temple is associated with the famous Rath Yatra festival. The temple flag changes direction with the wind and is considered a miracle. Non-Hindus are not allowed inside.',
'{"country": "India", "state": "Odisha", "city": "Puri", "address": "Grand Road, Puri", "pincode": "752001", "lat": 19.8048, "lng": 85.8314}',
'{"daily": "5:00 AM - 11:00 PM", "special": "Open 21 hours during festivals"}',
'{"phone": "+91-6752-222106", "email": "jagannath@templetrust.org", "website": "https://jagannath.nic.in"}',
'[{"time": "5:00 AM", "type": "Mangala Alati"}, {"time": "7:00 AM", "type": "Mailam"}, {"time": "10:00 AM", "type": "Madhyanha Dhupa"}, {"time": "8:00 PM", "type": "Sandhya Dhupa"}]',
'["Prasad Counter", "Accommodation", "Hospital", "Cloakroom", "Drinking Water", "Parking", "Security", "Tourist Information"]',
'{"indian": "Free", "special_darshan": "50-200 INR"}',
'["https://images.unsplash.com/photo-1624395149011-470cf6f6ec02?w=800"]',
4.8, true, true, null, 'UCJagannathPuri'),

-- 5. Meenakshi Temple, Madurai
('Meenakshi Amman Temple', 'Goddess Meenakshi & Lord Sundareswarar', 'Shaivism',
'A historic Hindu temple dedicated to Goddess Meenakshi and her consort Sundareswarar. Famous for its stunning Dravidian architecture and 14 gopurams (gateway towers).',
'The temple has been mentioned in Tamil literature dating back to the 7th century. The current structure was built between 1623 and 1655 CE by Tirumalai Nayak. The temple has 14 magnificent gopurams decorated with colorful sculptures.',
'{"country": "India", "state": "Tamil Nadu", "city": "Madurai", "address": "Madurai Main, Madurai", "pincode": "625001", "lat": 9.9195, "lng": 78.1193}',
'{"daily": "5:00 AM - 12:30 PM, 4:00 PM - 9:30 PM"}',
'{"phone": "+91-452-2345089", "email": "meenakshi@tnhrce.org", "website": "https://meenakshitemple.tn.gov.in"}',
'[{"time": "5:00 AM", "type": "Vishwaroopa Darshan"}, {"time": "6:30 AM", "type": "Kalasandhi Pooja"}, {"time": "12:00 PM", "type": "Uchikala Pooja"}, {"time": "9:00 PM", "type": "Arthajama Pooja"}]',
'["Prasad Counter", "Museum", "Audio Guide", "Photography Allowed", "Shopping Complex", "Parking", "Medical Room", "Tourist Guide"]',
'{"indian": "50 INR", "foreigner": "500 INR", "camera": "50 INR", "special_entry": "300 INR"}',
'["https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800"]',
4.9, true, true, null, 'UCMeenakshiTemple'),

-- 6. Konark Sun Temple
('Konark Sun Temple', 'Surya (Sun God)', 'Hinduism',
'UNESCO World Heritage Site, designed in the shape of a colossal chariot with 24 wheels. A masterpiece of Odia architecture and one of the most famous Brahmin sanctuaries.',
'Built in the 13th century by King Narasimhadeva I of the Eastern Ganga dynasty. The temple is designed as a gigantic chariot of the sun god Surya, with 24 elaborately carved stone wheels and pulled by seven horses.',
'{"country": "India", "state": "Odisha", "city": "Konark", "address": "Konark, Puri District", "pincode": "752111", "lat": 19.8876, "lng": 86.0945}',
'{"daily": "6:00 AM - 8:00 PM", "light_show": "7:00 PM - 8:00 PM"}',
'{"phone": "+91-6758-236821", "email": "konark@asi.org", "website": "https://konark.nic.in"}',
'[{"time": "Sunrise", "type": "Best viewing time"}, {"time": "7:00 PM", "type": "Light & Sound Show"}]',
'["Museum", "Archaeological Museum", "Light Show", "Cafeteria", "Souvenir Shop", "Guide Service", "Parking", "Photography Allowed"]',
'{"indian": "40 INR", "foreigner": "600 INR", "camera": "25 INR", "video": "25 INR"}',
'["https://images.unsplash.com/photo-1569097656240-07071ea29045?w=800"]',
4.7, true, false, null, null),

-- 7. Siddhivinayak Temple, Mumbai
('Siddhivinayak Temple', 'Lord Ganesha', 'Hinduism',
'One of the most visited and richest temples in Mumbai. The temple is dedicated to Lord Ganesha and attracts millions of devotees annually.',
'Built on 19 November 1801 by Laxman Vithu and Deubai Patil. The wooden doors to the sanctum are carved with images of the Ashtavinayak (the eight manifestations of Ganesha). The temple has a small mandap with the shrine for Siddhi Vinayak.',
'{"country": "India", "state": "Maharashtra", "city": "Mumbai", "address": "S K Bole Marg, Prabhadevi", "pincode": "400028", "lat": 19.0177, "lng": 72.8300}',
'{"daily": "5:30 AM - 9:50 PM", "tuesday": "VIP darshan available"}',
'{"phone": "+91-22-2430-3835", "email": "info@siddhivinayak.org", "website": "https://siddhivinayak.org"}',
'[{"time": "6:00 AM", "type": "Kakad Aarti"}, {"time": "12:00 PM", "type": "Madhyan Aarti"}, {"time": "9:00 PM", "type": "Shej Aarti"}]',
'["Prasad Counter", "Donation Counter", "Annadaan Facility", "Medical Room", "Cloakroom", "Online Darshan", "Live Streaming"]',
'{"indian": "Free", "special_darshan": "101 INR"}',
'["https://images.unsplash.com/photo-1597392955360-1cc0db7db2db?w=800"]',
4.7, true, true, 'https://www.siddhivinayak.org/live-darshan', 'UCSiddhivinayakTemple'),

-- 8. Kashi Vishwanath Temple
('Kashi Vishwanath Temple', 'Lord Shiva', 'Shaivism',
'One of the twelve Jyotirlingas, located in Varanasi. One of the most sacred Hindu temples dedicated to Lord Shiva.',
'The temple has been demolished and reconstructed several times. The current structure was built by Maharani Ahilya Bai Holkar of Indore in 1780. The gold plating on the towers was done by Maharaja Ranjit Singh in 1839.',
'{"country": "India", "state": "Uttar Pradesh", "city": "Varanasi", "address": "Kashi Vishwanath Gali, Varanasi", "pincode": "221001", "lat": 25.3109, "lng": 83.0108}',
'{"daily": "2:30 AM - 11:00 PM", "special": "Extended hours during festivals"}',
'{"phone": "+91-542-2392784", "email": "kvt@kvtemple.org", "website": "https://shrikashivishwanath.org"}',
'[{"time": "3:00 AM", "type": "Mangala Aarti"}, {"time": "11:15 AM", "type": "Bhog Aarti"}, {"time": "7:00 PM", "type": "Sandhya Aarti"}, {"time": "9:00 PM", "type": "Shringar Aarti"}]',
'["VIP Darshan", "Special Entry Pass", "Prasad Counter", "Security Check", "Cloakroom", "Medical Facility", "Wheelchair Access"]',
'{"indian": "Free", "special_darshan": "300 INR"}',
'["https://images.unsplash.com/photo-1548013146-72479768bada?w=800"]',
4.9, true, true, null, 'UCKashiVishwanath'),

-- 9. Amarnath Cave
('Amarnath Cave', 'Lord Shiva (Ice Lingam)', 'Shaivism',
'A famous shrine situated at an altitude of 3,888 meters in the Himalayas. The cave houses an ice stalagmite that resembles Shiva Lingam, which waxes and wanes with the phases of the moon.',
'According to legend, this is the cave where Lord Shiva revealed the secret of immortality to Goddess Parvati. The cave is open only during the summer months for the annual pilgrimage called Amarnath Yatra.',
'{"country": "India", "state": "Jammu & Kashmir", "city": "Pahalgam", "address": "Amarnath, Anantnag District", "pincode": "192126", "lat": 34.2164, "lng": 75.5147}',
'{"yatra_period": "July-August (40 days)", "timings": "Weather dependent"}',
'{"phone": "+91-1942-256407", "email": "amarnath@jksasb.nic.in", "website": "https://shriamarnathjishrine.com"}',
'[{"time": "Dawn", "type": "Ice Lingam Darshan"}, {"time": "Dusk", "type": "Evening Prayers"}]',
'["Medical Camps", "Helicopter Service", "Pony Service", "Langar Facilities", "Emergency Services", "Oxygen Support", "Communications"]',
'{"indian": "Registration: 100 INR", "helicopter": "3000 INR per sector", "insurance": "Included in registration"}',
'["https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800"]',
4.9, true, true, null, 'UCAmarnatJi'),

-- 10. Sai Baba Temple, Shirdi
('Shirdi Sai Baba Temple', 'Sai Baba', 'Universalism',
'One of the most visited pilgrimage sites in India, dedicated to Sai Baba who preached the importance of realization of God, faith and devotion. The temple attracts devotees from all religions.',
'Sai Baba lived in Shirdi from 1858 until his death in 1918. The temple was built after his samadhi. The Samadhi Temple contains the tomb of Sai Baba. The temple is managed by the Shri Saibaba Sansthan Trust.',
'{"country": "India", "state": "Maharashtra", "city": "Shirdi", "address": "Shirdi, Ahmednagar District", "pincode": "423109", "lat": 19.7645, "lng": 74.4769}',
'{"daily": "4:00 AM - 11:15 PM", "special": "Extended hours on Thursdays"}',
'{"phone": "+91-2423-258500", "email": "info@sai.org.in", "website": "https://sai.org.in"}',
'[{"time": "5:30 AM", "type": "Kakad Aarti"}, {"time": "12:00 PM", "type": "Madhyan Aarti"}, {"time": "6:45 PM", "type": "Dhoop Aarti"}, {"time": "10:30 PM", "type": "Shej Aarti"}]',
'["Online Booking", "Accommodation", "Prasad Counter", "Annadaan", "Medical Facility", "Parking", "Museum", "Library", "Donation Counter"]',
'{"indian": "Free", "vip_darshan": "100 INR", "special_darshan": "300 INR"}',
'["https://images.unsplash.com/photo-1604608672516-f1b9b1a6d89a?w=800"]',
4.8, true, true, 'https://www.sai.org.in/en/live-darshan', 'UCSaibabaShirdi');