-- Migration 5: Add FAQs and Calendar Events 2026

-- Add spiritual FAQs
INSERT INTO spiritual_faqs (question, answer, category, language, difficulty_level, source_references) VALUES
('What is the significance of 108 in Hinduism?', '108 is sacred because: 1) Distance from Earth to Sun is 108 times Sun''s diameter, 2) 27 constellations x 4 padas = 108, 3) 108 Upanishads, 4) 108 names of deities. Malas have 108 beads for japa meditation.', 'practices', 'en', 'beginner', '["Vedic Mathematics", "Yoga Sutras"]'),
('How to start a daily meditation practice?', 'Begin with 10-15 minutes at the same time daily, preferably morning. Sit comfortably, focus on breath or mantra. Start with guided meditations. Be consistent rather than perfect. Gradually increase duration.', 'meditation', 'en', 'beginner', '["Patanjali Yoga Sutras"]'),
('What is the difference between Bhakti and Jnana yoga?', 'Bhakti Yoga is the path of devotion through love of God. Jnana Yoga is the path of knowledge through self-inquiry. Both lead to liberation. Bhakti suits emotional temperaments; Jnana suits intellectual seekers.', 'philosophy', 'en', 'intermediate', '["Bhagavad Gita"]'),
('Why do Hindus worship multiple deities?', 'Hinduism recognizes One Supreme Reality (Brahman) manifesting in infinite forms. Different deities represent different aspects - Ganesha for beginnings, Lakshmi for prosperity, Saraswati for knowledge. It accommodates diverse spiritual needs.', 'philosophy', 'en', 'beginner', '["Rig Veda", "Upanishads"]'),
('What is the importance of Tulsi plant?', 'Tulsi (Holy Basil) is sacred to Vishnu and considered goddess Lakshmi''s manifestation. It purifies air, has medicinal properties, and sanctifies homes. Daily worship brings prosperity and protection.', 'rituals', 'en', 'beginner', '["Padma Purana"]'),
('How to observe Ekadashi fast?', 'Ekadashi falls on 11th lunar day twice monthly. Devotees fast from grains, beans, and certain vegetables. Minimum is avoiding rice and wheat. Spend time in prayer, reading scriptures, and chanting. Break fast next day after sunrise.', 'practices', 'en', 'intermediate', '["Garuda Purana"]'),
('What is the significance of Rudraksha beads?', 'Rudraksha are seeds from Elaeocarpus tree, believed to be Lord Shiva''s tears. Different faces (mukhis) have different benefits. 5-mukhi is most common for general well-being. Worn for spiritual protection and meditation.', 'practices', 'en', 'intermediate', '["Shiva Purana"]'),
('What is Sandhya Vandana?', 'Sandhya Vandana is the daily ritual performed at dawn, noon, and dusk. It includes pranayama, Gayatri mantra chanting, and meditation. It connects the practitioner to cosmic rhythms and maintains spiritual discipline.', 'rituals', 'en', 'intermediate', '["Manu Smriti"]'),
('How does karma affect rebirth?', 'Karma (actions) creates impressions (samskaras) that determine future births. Good karma leads to favorable births, bad karma to suffering. Liberation (moksha) comes when karma is exhausted through spiritual practice.', 'philosophy', 'en', 'intermediate', '["Bhagavad Gita", "Brahma Sutras"]'),
('What mantras should beginners start with?', 'Start with Om, then Gayatri Mantra for wisdom, Om Namah Shivaya for peace, Hare Krishna for devotion, or Ganesh mantra for removing obstacles. Consistency matters more than quantity. Even 10 minutes daily transforms consciousness.', 'mantras', 'en', 'beginner', '["Yoga Sutras"]');

-- Add 2026 calendar events
INSERT INTO calendar_events (title, event_type, date, description, significance, rituals, regional_significance) VALUES
('Kartik Purnima 2026', 'purnima', '2026-11-04', 'Full moon day in Kartik month, marks end of Chaturmas', 'Extremely auspicious for charity and holy bath. Dev Diwali celebrated in Varanasi.', '["Holy bath", "Lighting diyas", "Charity", "Tulsi Vivah preparations"]', '["Varanasi", "Pushkar", "All India"]'),
('Chhath Puja 2026', 'festival', '2026-11-08', 'Ancient Vedic festival dedicated to Sun God and Chhathi Maiya', 'Four-day rigorous festival for well-being of family. Involves standing in water offering arghya to Sun.', '["Nahay Khay", "Kharna", "Sandhya Arghya", "Usha Arghya"]', '["Bihar", "Jharkhand", "UP", "Nepal"]'),
('Tulsi Vivah 2026', 'festival', '2026-11-09', 'Ceremonial marriage of Tulsi plant to Lord Vishnu/Krishna', 'Marks beginning of Hindu wedding season. Tulsi plant dressed as bride.', '["Tulsi puja", "Wedding rituals", "Singing", "Prasad distribution"]', '["Maharashtra", "All India"]'),
('Gita Jayanti 2026', 'festival', '2026-12-03', 'Anniversary of Bhagavad Gita discourse by Lord Krishna to Arjuna', 'Day Gita was revealed on Kurukshetra battlefield. Special recitations worldwide.', '["Complete Gita recitation", "Discourses", "Satsang"]', '["Kurukshetra", "ISKCON temples", "All India"]'),
('Vat Savitri 2026', 'vrat', '2026-05-27', 'Married women fast for husband''s longevity', 'Story of Savitri who won back husband from Yama. Women tie thread around banyan tree.', '["Vat tree puja", "Fasting", "Tying sacred thread", "Prayers for husband"]', '["North India", "Maharashtra"]'),
('Ahoi Ashtami 2026', 'vrat', '2026-10-17', 'Mothers fast for well-being of children', 'Observed 8 days before Diwali. Story of woman who accidentally killed young mongoose.', '["Ahoi Mata puja", "Drawing Ahoi", "Star-sighting fast break"]', '["North India"]'),
('Dev Uthani Ekadashi 2026', 'ekadashi', '2026-11-02', 'Day when Lord Vishnu awakens from four-month sleep', 'Marks end of Chaturmas. Weddings and auspicious activities resume.', '["Vishnu puja", "Tulsi puja", "Awakening ceremony"]', '["All India"]'),
('Pausha Putrada Ekadashi 2026', 'ekadashi', '2026-01-10', 'Ekadashi for blessing of sons', 'Extremely auspicious for couples desiring children.', '["Fasting", "Vishnu worship", "Charity"]', '["All India"]'),
('Phulera Dooj 2026', 'festival', '2026-02-28', 'Festival celebrating Holi preparations with flowers', 'Two days before Holi, Krishna-Radha celebrated with flowers.', '["Flower offerings", "Krishna puja", "Singing Holi songs"]', '["Braj region", "Mathura", "Vrindavan"]'),
('Guru Purnima 2026', 'purnima', '2026-07-21', 'Day honoring spiritual teachers', 'Birth anniversary of Ved Vyasa. Students honor their gurus.', '["Guru puja", "Offering dakshina", "Discourses", "Pada puja"]', '["All India", "Nepal"]');