-- Migration 4: Add new temples with comprehensive data

INSERT INTO temples (name, primary_deity, tradition, description, history, location, visiting_hours, facilities, entrance_fee, live_darshan_url, verified, rating) VALUES
('Jagannath Temple, Puri', 'Lord Jagannath', 'Vaishnavism', 'One of the Char Dham pilgrimage sites and home to the famous Rath Yatra. Lord Jagannath with siblings Balabhadra and Subhadra are worshipped here. Non-Hindus are not permitted inside. The temple kitchen serves Mahaprasad that feeds thousands daily.', 
'Built in the 12th century by King Anantavarman Chodaganga Deva. The temple has survived multiple invasions and remains one of India''s most sacred sites. The annual Rath Yatra draws millions of devotees.', 
'{"city": "Puri", "state": "Odisha", "country": "India", "address": "Grand Road, Puri", "coordinates": {"lat": 19.8048, "lng": 85.8181}}',
'{"morning": "5:00 AM - 12:00 PM", "evening": "4:00 PM - 11:00 PM"}',
'["Mahaprasad", "Temple kitchen", "Dharamshala", "Parking", "Shoe counter"]',
'{"indian": "Free", "foreign": "Not permitted"}',
'https://www.youtube.com/watch?v=jagannath_live', true, 4.8),

('Meenakshi Temple, Madurai', 'Goddess Meenakshi and Lord Sundareswarar', 'Shaivism', 'A historic Hindu temple located on the southern bank of the Vaigai River. Famous for its stunning Dravidian architecture with 14 gateway towers (gopurams) covered with thousands of colorful sculptures. The temple complex covers 14 acres and is a major pilgrimage destination.', 
'Rebuilt by Nayak kings in 17th century after Malik Kafur''s destruction. Originally built by Pandya kings around 6th century BCE. Legend says Lord Shiva came here to marry Meenakshi, the princess with fish-shaped eyes.', 
'{"city": "Madurai", "state": "Tamil Nadu", "country": "India", "address": "Meenakshi Temple Complex", "coordinates": {"lat": 9.9195, "lng": 78.1193}}',
'{"morning": "5:00 AM - 12:30 PM", "evening": "4:00 PM - 10:00 PM"}',
'["Museum", "Thousand Pillar Hall", "Golden Lotus Tank", "Guided tours", "Photography in outer areas"]',
'{"indian": "Free", "foreign": "₹50", "camera": "₹50"}',
'https://www.youtube.com/watch?v=meenakshi_temple', true, 4.7),

('Vaishno Devi Temple', 'Goddess Vaishno Devi', 'Shaktism', 'One of the most revered Hindu temples dedicated to Shakti, located in the Trikuta Mountains. Pilgrims trek 12 km to reach the holy cave. The three natural rock formations represent Mahakali, Mahalakshmi, and Mahasaraswati. Attracts over 10 million pilgrims annually.', 
'The cave shrine is believed to be over 700 years old. According to legend, the goddess hid in this cave to escape a demon. The shrine was made famous by Pandit Sridhar and later promoted by Vaishno Devi Shrine Board.', 
'{"city": "Katra", "state": "Jammu & Kashmir", "country": "India", "address": "Trikuta Mountains, Katra", "coordinates": {"lat": 33.0302, "lng": 74.9489}}',
'{"morning": "5:00 AM to continuous", "evening": "Open 24 hours during peak seasons"}',
'["Helicopter service", "Pony service", "Palki service", "Bhojanalaya", "Dharamshala", "ATMs", "Medical facilities"]',
'{"indian": "Free", "helicopter": "₹2500 round trip"}',
'https://www.youtube.com/watch?v=vaishno_devi_live', true, 4.9),

('Siddhivinayak Temple, Mumbai', 'Lord Ganesha', 'Shaivism', 'One of the richest temples in India, dedicated to Lord Ganesha. Famous for granting wishes (Navasachi). The idol is carved from a single black stone with trunk turned right, which is rare. Bollywood celebrities and politicians regularly visit for blessings.', 
'Built in 1801 by Laxman Vithu and Deubai Patil. The original small temple expanded significantly after generous donations. Now managed by the Siddhivinayak Temple Trust which supports numerous charitable activities.', 
'{"city": "Mumbai", "state": "Maharashtra", "country": "India", "address": "Prabhadevi, Mumbai", "coordinates": {"lat": 19.0169, "lng": 72.8309}}',
'{"morning": "5:30 AM - 12:00 PM", "evening": "4:00 PM - 9:30 PM", "tuesday": "Open for 21 hours"}',
'["VIP darshan", "Online booking", "Prasad counter", "Air-conditioned hall", "Security"]',
'{"indian": "Free", "vip": "₹500"}',
'https://www.youtube.com/watch?v=siddhivinayak_live', true, 4.6),

('Akshardham Temple, Delhi', 'Lord Swaminarayan', 'Swaminarayan Sampradaya', 'A stunning modern temple complex showcasing India''s ancient art, culture, and spirituality. Features intricately carved pink sandstone and Italian marble. The main monument displays the life of Swaminarayan. Recognized by Guinness World Records as world''s largest comprehensive Hindu temple.', 
'Opened in 2005, built by BAPS in just 5 years. Over 8,000 volunteers and 3,000 artisans contributed. The temple was built without steel using traditional methods. It sits on 100 acres along the Yamuna.', 
'{"city": "New Delhi", "state": "Delhi", "country": "India", "address": "Noida Mor, Delhi", "coordinates": {"lat": 28.6127, "lng": 77.2773}}',
'{"morning": "9:30 AM - 6:30 PM", "closed": "Monday"}',
'["Boat ride", "Musical fountain", "Exhibition halls", "Garden", "Food court", "No photography inside"]',
'{"indian": "Free temple, ₹220 exhibitions", "foreign": "₹220 exhibitions"}',
'https://www.youtube.com/watch?v=akshardham_delhi', true, 4.8),

('Mahakaleshwar Temple, Ujjain', 'Lord Shiva as Mahakal', 'Shaivism', 'One of the 12 Jyotirlingas of Lord Shiva, with the lingam being svayambhu (self-manifested). Famous for the Bhasma Aarti performed with cremation ash at 4 AM. The lingam is believed to be dakshinamurti (south-facing), which is unique among Jyotirlingas.', 
'Ancient temple mentioned in many Puranas. Destroyed by Iltutmish in 1235, rebuilt by Marathas in 18th century. The current structure was built by Ranoji Shinde. Ujjain is one of the four Kumbh Mela sites.', 
'{"city": "Ujjain", "state": "Madhya Pradesh", "country": "India", "address": "Jaisinghpura, Ujjain", "coordinates": {"lat": 23.1828, "lng": 75.7684}}',
'{"bhasma_aarti": "4:00 AM", "morning": "4:00 AM - 11:00 PM"}',
'["Bhasma Aarti registration", "VIP darshan", "Prasad", "Tank for holy bath"]',
'{"indian": "Free", "bhasma_aarti": "₹250 online booking"}',
'https://www.youtube.com/watch?v=mahakaleshwar_live', true, 4.7),

('Shirdi Sai Baba Temple', 'Sai Baba of Shirdi', 'Universal', 'One of the most visited pilgrimage centers in the world, dedicated to the saint Sai Baba who lived in Shirdi from 1858 to 1918. The Samadhi Mandir houses his tomb. Daily rituals include Kakad Aarti at 4:15 AM, Madhyan Aarti, Dhoop Aarti, and Shej Aarti. Attracts devotees of all religions.', 
'Sai Baba arrived in Shirdi as a young fakir and stayed until his mahasamadhi. The small village transformed into a major pilgrimage site. The Sai Baba Sansthan Trust manages the temple and numerous charitable activities including free meals for over 50,000 pilgrims daily.', 
'{"city": "Shirdi", "state": "Maharashtra", "country": "India", "address": "Shirdi, Ahmednagar District", "coordinates": {"lat": 19.7663, "lng": 74.4773}}',
'{"morning": "4:00 AM - 3:00 PM", "evening": "3:00 PM - 11:30 PM"}',
'["Free accommodation", "Free meals (Prasadalaya)", "Medical facilities", "Online booking", "VIP darshan"]',
'{"indian": "Free", "vip": "₹200"}',
'https://www.youtube.com/watch?v=shirdi_sai_live', true, 4.9),

('Padmanabhaswamy Temple, Thiruvananthapuram', 'Lord Vishnu as Padmanabha', 'Vaishnavism', 'One of the richest temples in the world with treasures valued at over $20 billion. Lord Vishnu reclines on the serpent Anantha. Built in Dravidian style with tall gopuram. Only Hindus are allowed and men must wear dhoti, women must wear sari or churidar.', 
'Ancient temple mentioned in Sangam literature. The current structure dates to 8th century. Governed by Travancore Royal Family. In 2011, massive treasures were discovered in underground vaults, making it the wealthiest place of worship.', 
'{"city": "Thiruvananthapuram", "state": "Kerala", "country": "India", "address": "West Nada, Thiruvananthapuram", "coordinates": {"lat": 8.4835, "lng": 76.9435}}',
'{"morning": "3:30 AM - 12:00 PM", "evening": "5:00 PM - 8:00 PM"}',
'["Strict dress code required", "Darshan queue", "Special puja booking"]',
'{"indian": "Free", "special_darshan": "₹50-100"}',
'https://www.youtube.com/watch?v=padmanabhaswamy_live', true, 4.8),

('Lingaraj Temple, Bhubaneswar', 'Lord Shiva as Lingaraja', 'Shaivism', 'The largest and most important temple in Bhubaneswar, representing the finest example of Kalinga architecture. The main tower is 180 feet tall. The lingam is both Shiva and Vishnu combined (Harihara). Non-Hindus can view from a platform outside.', 
'Built in 11th century by the Somavamsi dynasty. Represents 1100 years of temple building in Bhubaneswar. The temple compound covers 250,000 sq ft with 150 smaller shrines. Stone carvings depict scenes from Shiva''s life.', 
'{"city": "Bhubaneswar", "state": "Odisha", "country": "India", "address": "Lingaraj Nagar, Bhubaneswar", "coordinates": {"lat": 20.2385, "lng": 85.8333}}',
'{"morning": "5:00 AM - 12:30 PM", "evening": "3:30 PM - 9:00 PM"}',
'["Non-Hindu viewing platform", "Bindusagar tank", "Prasad"]',
'{"indian": "Free"}',
NULL, true, 4.6),

('Nataraja Temple, Chidambaram', 'Lord Shiva as Nataraja', 'Shaivism', 'One of the five Pancha Bhuta Stalas representing Akasha (space). Lord Shiva is worshipped as the cosmic dancer. The temple is famous for the Chidambara Rahasyam (secret of Chidambaram) - an empty space representing formless god. Managed by Dikshitars, a hereditary Brahmin community.', 
'Built during the Chola period, 10th century. Underwent renovations by various dynasties. The bronze Nataraja icon created here became the most famous representation of Hindu art. The temple covers 40 acres with four towering gopurams.', 
'{"city": "Chidambaram", "state": "Tamil Nadu", "country": "India", "address": "Chidambaram Town", "coordinates": {"lat": 11.3991, "lng": 79.6937}}',
'{"morning": "6:00 AM - 12:00 PM", "evening": "5:00 PM - 10:00 PM"}',
'["Guided tours", "Photography in outer areas", "Tank", "Museum"]',
'{"indian": "Free", "special_darshan": "₹100"}',
NULL, true, 4.5);