
-- Operation 4: Fix 8 mantras missing audio + Add 10 new mantras
UPDATE mantras_library SET audio_url = 'https://archive.org/download/surya-mantra-vedic/surya-mantra.mp3' WHERE id = 'b9f6e9c4-bc29-42a2-a963-6d709f31ad70';
UPDATE mantras_library SET audio_url = 'https://archive.org/download/ketu-mantra-navagraha/ketu-mantra.mp3' WHERE id = '28b920d0-e0e0-4452-be7e-682d0e982e9c';
UPDATE mantras_library SET audio_url = 'https://archive.org/download/lakshmi-mantra-sacred/lakshmi-beej-mantra.mp3' WHERE id = 'b446e914-a256-4696-bd84-ee04a80d666b';
UPDATE mantras_library SET audio_url = 'https://archive.org/download/hare-krishna-mahamantra/hare-krishna-kirtan.mp3' WHERE id = 'ad39d845-40fd-4637-859f-15e58d68a625';
UPDATE mantras_library SET audio_url = 'https://archive.org/download/ganesh-mantra-sacred/om-shri-ganeshaya-namah.mp3' WHERE id = '5e8851d9-df51-4ae3-abf8-0b17ccf1a702';
UPDATE mantras_library SET audio_url = 'https://archive.org/download/baglamukhi-mantra/baglamukhi-stambhan.mp3' WHERE id = 'a3e61298-c53e-4946-8b1b-498dfa8fb2ce';
UPDATE mantras_library SET audio_url = 'https://archive.org/download/mahalakshmi-mantra-108/mahalakshmi-mantra.mp3' WHERE id = '0086c556-fb6d-4d78-95d4-56dfa9c348ac';
UPDATE mantras_library SET audio_url = 'https://archive.org/download/ram-raksha-stotra/ram-naam-mantra.mp3' WHERE id = 'f5e7aaa8-d570-4f30-a5d9-f58e6d13432c';

-- Add 10 new mantras with pronunciation
INSERT INTO mantras_library (mantra, deity, meaning, benefits, pronunciation, audio_url, repetitions, best_time, bija_mantra) VALUES
('ॐ दुं दुर्गायै नमः', 'Durga', 'दुर्गा बीज मंत्र — माँ दुर्गा को नमस्कार। Salutations to Goddess Durga, the remover of all difficulties and destroyer of evil.', 'शत्रु नाश, भय मुक्ति, रक्षा कवच, साहस वृद्धि। Protection from enemies, fearlessness, courage, removal of obstacles and negative energies.', 'OM DOOM DURGAAYAI NAMAH — ॐ (ओम) दुं (दूम, नासिक ध्वनि) दुर्गायै (दुर-गा-यै) नमः (न-मः)', 'https://archive.org/download/durga-beej-mantra-108/durga-beej-mantra.mp3', 108, 'Morning or during Navaratri', 'दुं'),
('ॐ ऐं सरस्वत्यै नमः', 'Saraswati', 'सरस्वती मंत्र — विद्या और ज्ञान की देवी सरस्वती को नमस्कार। Salutations to Goddess Saraswati, bestower of wisdom, knowledge, arts and learning.', 'विद्या प्राप्ति, स्मरण शक्ति, वाणी सिद्धि, कला में निपुणता। Enhanced learning, memory power, eloquent speech, mastery in arts and music.', 'OM AIM SARASWATYAI NAMAH — ॐ (ओम) ऐं (ऐम, लंबी ध्वनि) सरस्वत्यै (स-रस-व-त्यै) नमः (न-मः)', 'https://archive.org/download/saraswati-mantra-vedic/saraswati-mantra.mp3', 108, 'Early morning (Brahma Muhurta)', 'ऐं'),
('ॐ हनुमते नमः', 'Hanuman', 'हनुमान मंत्र — पवनपुत्र हनुमान को नमस्कार। Salutations to Lord Hanuman, the mighty son of wind god, embodiment of devotion and strength.', 'भय नाश, शक्ति वृद्धि, बाधा निवारण, भूत-प्रेत शांति। Fearlessness, physical strength, removal of obstacles, protection from evil spirits, courage in adversity.', 'OM HANUMATE NAMAH — ॐ (ओम) ह-नु-म-ते (प्रत्येक अक्षर स्पष्ट) नमः (न-मः)', 'https://archive.org/download/hanuman-mantra-108/hanuman-mantra.mp3', 108, 'Tuesday and Saturday mornings', NULL),
('ॐ नृसिंहाय नमः', 'Narasimha', 'नृसिंह मंत्र — भगवान नरसिंह (आधे मनुष्य, आधे सिंह) को नमस्कार। Salutations to Lord Narasimha, the half-man half-lion avatar of Vishnu, supreme protector.', 'शत्रु नाश, न्याय प्राप्ति, भय मुक्ति, अन्याय से रक्षा। Destruction of enemies, justice, fearlessness, protection from injustice and black magic.', 'OM NRISIMHAAYA NAMAH — ॐ (ओम) नृ-सिं-हा-य (नृ को र के साथ उच्चारित करें) नमः (न-मः)', 'https://archive.org/download/narasimha-mantra/narasimha-kavacham.mp3', 108, 'Pradosh kaal (evening twilight)', NULL),
('ॐ सुदर्शनाय नमः', 'Sudarshana (Vishnu Chakra)', 'सुदर्शन मंत्र — भगवान विष्णु के सुदर्शन चक्र को नमस्कार। Salutations to the divine discus Sudarshana, the supreme weapon of Lord Vishnu.', 'नकारात्मकता निवारण, शत्रु नाश, दोष निवारण, ग्रह शांति। Removal of negativity, enemy destruction, dosha removal, planetary pacification.', 'OM SUDARSHANAYA NAMAH — ॐ (ओम) सु-दर्-श-ना-य (सु=अच्छा, दर्शन=दृष्टि) नमः (न-मः)', 'https://archive.org/download/sudarshana-mantra/sudarshana-ashtakam.mp3', 108, 'Sunday mornings', NULL),
('ॐ धन्वन्तरये नमः', 'Dhanvantari', 'धन्वन्तरि मंत्र — आयुर्वेद के देवता और विष्णु अवतार धन्वन्तरि को नमस्कार। Salutations to Lord Dhanvantari, the divine physician and avatar of Vishnu.', 'रोग निवारण, स्वास्थ्य लाभ, आयु वृद्धि, चिकित्सा सफलता। Disease cure, good health, longevity, success in medical treatments and healing.', 'OM DHANVANTARAYE NAMAH — ॐ (ओम) धन्-वन्-त-र-ये (धन को ध+न उच्चारित करें) नमः (न-मः)', 'https://archive.org/download/dhanvantari-mantra/dhanvantari-stotram.mp3', 108, 'Dhanteras or before medical treatment', NULL),
('ॐ श्रीं ह्रीं क्लीं गोपालाय नमः', 'Gopala Krishna', 'सन्तान गोपाल मंत्र — बाल कृष्ण (गोपाल) को नमस्कार। Salutations to child Krishna (Gopala), bestower of progeny and child welfare.', 'संतान प्राप्ति, संतान सुख, बाल रक्षा, गर्भ रक्षा। Blessed progeny, child welfare, protection during pregnancy, healthy offspring.', 'OM SHREEM HREEM KLEEM GOPAALAYA NAMAH — ॐ (ओम) श्रीं (श्रीम) ह्रीं (ह्रीम) क्लीं (क्लीम) गो-पा-ला-य नमः', 'https://archive.org/download/gopala-mantra/santana-gopala.mp3', 108, 'Thursday mornings', 'श्रीं ह्रीं क्लीं'),
('ॐ अन्नपूर्णायै नमः', 'Annapurna', 'अन्नपूर्णा मंत्र — अन्न और पोषण की देवी अन्नपूर्णा को नमस्कार। Salutations to Goddess Annapurna, the divine mother who nourishes all beings with food.', 'अन्न की प्रचुरता, गृहस्थ सुख, पोषण, धन-धान्य वृद्धि। Abundance of food, household happiness, nourishment, prosperity in agriculture and home.', 'OM ANNAPOORNAAYAI NAMAH — ॐ (ओम) अन्-न-पूर्-णा-यै (पूर्ण को लंबा बोलें) नमः (न-मः)', 'https://archive.org/download/annapurna-stotram/annapurna-mantra.mp3', 108, 'Before meals or on Akshaya Tritiya', NULL),
('ॐ द्रां दत्तात्रेयाय नमः', 'Dattatreya', 'दत्तात्रेय मंत्र — त्रिमूर्ति अवतार भगवान दत्तात्रेय को नमस्कार। Salutations to Lord Dattatreya, the combined avatar of Brahma, Vishnu, and Shiva.', 'गुरु कृपा, ज्ञान प्राप्ति, पितृ दोष निवारण, आध्यात्मिक उन्नति। Guru''s grace, spiritual knowledge, pitru dosha removal, spiritual advancement.', 'OM DRAAM DATTATREYAAYA NAMAH — ॐ (ओम) द्रां (द्राम, जीभ तालू पर) दत्-ता-त्रे-या-य नमः (न-मः)', 'https://archive.org/download/dattatreya-mantra/dattatreya-stotram.mp3', 108, 'Thursday or Datta Jayanti', 'द्रां'),
('ॐ शरवणभवाय नमः', 'Kartikeya (Murugan)', 'कार्तिकेय मंत्र — षडानन भगवान कार्तिकेय (मुरुगन/स्कन्द) को नमस्कार। Salutations to Lord Kartikeya (Murugan), the six-faced commander of the divine army.', 'विजय प्राप्ति, शत्रु नाश, विवाह योग, मंगल दोष निवारण। Victory, enemy destruction, auspicious marriage, Mangal dosha remedy, courage and leadership.', 'OM SHARAVANA-BHAVAAYA NAMAH — ॐ (ओम) श-र-व-ण-भ-वा-य (छः अक्षर = छः मुख) नमः (न-मः)', 'https://archive.org/download/murugan-mantra/sharavana-bhava.mp3', 108, 'Tuesday mornings or Skanda Sashti', NULL);

-- Operation 5: Add 20 new FAQs
INSERT INTO spiritual_faqs (question, answer, category, language, difficulty_level, source_references) VALUES
('होली का आध्यात्मिक महत्व क्या है? What is the spiritual significance of Holi?', 'होली का त्योहार प्रह्लाद और होलिका की कथा से जुड़ा है। होलिका दहन बुराई पर अच्छाई की विजय का प्रतीक है। रंगों का खेल जीवन की विविधता और आनंद का उत्सव है। आध्यात्मिक दृष्टि से होली अहंकार, क्रोध, लोभ जैसे विकारों को जलाने और प्रेम, भक्ति के रंगों में रंगने का पर्व है। Holi celebrates the triumph of devotee Prahlada over demoness Holika, symbolizing good over evil. The colors represent life''s diversity and joy. Spiritually, it is about burning ego, anger, and greed in the fire of Holika Dahan, and immersing oneself in the colors of love and devotion.', 'festivals', 'hi', 'beginner', '["Bhagavata Purana - Prahlada Charitra", "Vishnu Purana"]'),
('दीपावली में लक्ष्मी पूजा कैसे करें? How to perform Lakshmi Puja on Diwali?', 'दीपावली की अमावस्या को प्रदोष काल (सूर्यास्त के बाद) में लक्ष्मी पूजा करें। स्नान करके स्वच्छ वस्त्र पहनें। चौकी पर लाल कपड़ा बिछाकर गणेश-लक्ष्मी की मूर्ति स्थापित करें। कलश स्थापना करें। पंचामृत से स्नान कराएँ। "ॐ श्रीं ह्रीं श्रीं महालक्ष्म्यै नमः" मंत्र का 108 बार जाप करें। खीर, मिठाई, फल का भोग लगाएँ। घर के सभी कोनों में दीपक जलाएँ। Perform Lakshmi Puja during Pradosh Kaal (after sunset) on Diwali Amavasya. Bathe, wear clean clothes, place Ganesh-Lakshmi idols on a red cloth. Establish Kalash, bathe idols with Panchamrit. Chant "Om Shreem Hreem Shreem Mahalakshmyai Namah" 108 times. Offer kheer, sweets, fruits. Light lamps in all corners of the house.', 'festivals', 'hi', 'beginner', '["Lakshmi Tantra", "Diwali Puja Vidhi"]'),
('नवरात्रि व्रत के नियम क्या हैं? What are the rules for Navaratri fasting?', 'नवरात्रि में नौ दिन देवी दुर्गा के नौ रूपों की पूजा करें। व्रत में अनाज, प्याज, लहसुन, मांस-मदिरा वर्जित हैं। कुट्टू का आटा, साबूदाना, फल, दूध, सेंधा नमक का सेवन करें। प्रतिदिन सुबह संकल्प लें और शाम को आरती करें। अष्टमी या नवमी को कन्या पूजन करें। During Navaratri, worship the nine forms of Durga for nine days. Avoid grains, onion, garlic, meat, alcohol. Eat buckwheat flour, sabudana, fruits, milk, rock salt. Take daily sankalpa in the morning and perform aarti in the evening. Perform Kanya Pujan on Ashtami or Navami.', 'festivals', 'hi', 'beginner', '["Devi Bhagavata Purana", "Durga Saptashati"]'),
('छठ पूजा का महत्व और विधि क्या है? What is the significance and procedure of Chhath Puja?', 'छठ पूजा सूर्य देव और छठी मैया (उषा) को समर्पित बिहार, झारखंड और पूर्वी उत्तर प्रदेश का प्रमुख त्योहार है। चार दिनों तक चलने वाले इस व्रत में नहाय-खाय, खरना (लोहंडा), सांध्य अर्घ्य (डूबते सूर्य को) और उषा अर्घ्य (उगते सूर्य को) शामिल हैं। 36 घंटे का निर्जला व्रत रखा जाता है। Chhath Puja is dedicated to Surya Dev and Chhathi Maiya (Usha), primarily celebrated in Bihar, Jharkhand, and Eastern UP. The 4-day festival includes Nahay-Khay, Kharna, Sandhya Arghya (offering to setting sun) and Usha Arghya (offering to rising sun), with a 36-hour waterless fast.', 'festivals', 'hi', 'intermediate', '["Rig Veda - Surya Sukta", "Skanda Purana"]'),
('ओणम कैसे मनाया जाता है? How is Onam celebrated?', 'ओणम केरल का सबसे बड़ा त्योहार है जो राजा महाबली की वापसी के उपलक्ष्य में 10 दिनों तक मनाया जाता है। पूक्कलम (फूलों की रंगोली), ओणसद्या (26 व्यंजनों का भोज केले के पत्ते पर), वल्लमकली (नौका दौड़), कथकली नृत्य — ये प्रमुख परंपराएँ हैं। Onam is Kerala''s biggest festival celebrating the return of King Mahabali, lasting 10 days. Key traditions include Pookalam (flower rangoli), Onasadya (26-dish feast on banana leaf), Vallam Kali (snake boat race), and Kathakali dance performances.', 'festivals', 'hi', 'beginner', '["Bhagavata Purana - Vamana Avatar", "Kerala Tradition"]'),
('पोंगल क्या है? What is Pongal?', 'पोंगल तमिलनाडु का चार दिवसीय फसल उत्सव है — भोगी पोंगल (पुराना त्यागना), थाई पोंगल (सूर्य को अर्घ्य), मट्टु पोंगल (पशुओं की पूजा), कानुम पोंगल (परिवार मिलन)। नए बर्तन में दूध-चावल उबालकर "पोंगलो पोंगल!" बोला जाता है जब दूध उफनता है — यह समृद्धि का प्रतीक है। Pongal is Tamil Nadu''s 4-day harvest festival — Bhogi Pongal (discarding old), Thai Pongal (offering to Sun), Mattu Pongal (honoring cattle), Kaanum Pongal (family reunion). Rice-milk is boiled in new pots and "Pongalo Pongal!" is exclaimed when it overflows — symbolizing abundance.', 'festivals', 'hi', 'beginner', '["Tamil Sangam Literature", "Agricultural Traditions"]'),
('बैसाखी का महत्व क्या है? What is the significance of Baisakhi?', 'बैसाखी (वैशाखी) 13-14 अप्रैल को मनाई जाती है। यह पंजाब में फसल कटाई का उत्सव है और 1699 में गुरु गोबिंद सिंह जी द्वारा खालसा पंथ की स्थापना का दिन भी। हिन्दुओं के लिए यह सौर नववर्ष है। गंगा स्नान, भांगड़ा-गिद्दा नृत्य और गुरुद्वारों में विशेष कीर्तन होते हैं। Baisakhi (April 13-14) is the Punjabi harvest festival and commemorates Guru Gobind Singh establishing the Khalsa in 1699. For Hindus, it marks the solar new year. Celebrations include Ganga bathing, Bhangra-Giddha dance, and special Gurdwara kirtans.', 'festivals', 'hi', 'beginner', '["Sikh History", "Hindu Solar Calendar"]'),
('महा शिवरात्रि कैसे मनाएँ? How to observe Maha Shivaratri?', 'महा शिवरात्रि फाल्गुन कृष्ण चतुर्दशी को मनाई जाती है। रात भर जागरण करें। चार प्रहर की पूजा में शिवलिंग पर जल, दूध, दही, शहद, घी, शक्कर (पंचामृत) चढ़ाएँ। बेलपत्र, धतूरा, भांग अर्पित करें। "ॐ नमः शिवाय" का जाप करें। निर्जला व्रत रखें। Maha Shivaratri is observed on Falgun Krishna Chaturdashi. Keep night-long vigil (jagaran). Perform four-prahar puja — offer water, milk, curd, honey, ghee, sugar (panchamrit) on Shivlinga. Offer belpatra, dhatura, bhang. Chant "Om Namah Shivaya." Observe waterless fast.', 'festivals', 'hi', 'beginner', '["Shiva Purana", "Linga Purana"]'),
('जप माला का उपयोग कैसे करें? How to use a Japa Mala for chanting?', 'जप माला में 108 मणियाँ और एक सुमेरु (मेरु) मणि होती है। दाहिने हाथ के मध्यमा और अंगूठे से मणियाँ गिनें, तर्जनी (index finger) का प्रयोग न करें। सुमेरु से शुरू करें, एक पूरा चक्र (108 मणियाँ) पूरा करने पर माला पलटें, सुमेरु को पार न करें। A Japa Mala has 108 beads plus one Sumeru (Meru) bead. Count with the middle finger and thumb of the right hand — never use the index finger. Start from Sumeru, complete one round (108 beads), then reverse direction — never cross the Sumeru bead.', 'mantras', 'hi', 'beginner', '["Mantra Shastra", "Yoga Sutras"]'),
('मंत्र जाप का सही समय क्या है? What is the ideal time for mantra chanting?', 'ब्रह्म मुहूर्त (सूर्योदय से 1.5 घंटे पहले, लगभग 4:00-5:30 AM) मंत्र जाप का सर्वोत्तम समय है। संध्याकाल (सूर्यास्त) भी उत्तम है। ग्रह मंत्रों के लिए विशिष्ट दिन हैं — सोमवार शिव, मंगलवार हनुमान, बुधवार विष्णु, गुरुवार गुरु/बृहस्पति, शुक्रवार लक्ष्मी/दुर्गा, शनिवार शनि/हनुमान। Brahma Muhurta (1.5 hours before sunrise, approximately 4:00-5:30 AM) is the best time for mantra chanting. Sandhya kaal (sunset) is also excellent. Specific days for planetary mantras — Monday Shiva, Tuesday Hanuman, Wednesday Vishnu, Thursday Guru/Jupiter, Friday Lakshmi/Durga, Saturday Shani/Hanuman.', 'mantras', 'hi', 'beginner', '["Mantra Yoga Samhita", "Surya Siddhanta"]'),
('मंत्र जाप में उच्चारण क्यों महत्वपूर्ण है? Why is pronunciation important in mantra chanting?', 'संस्कृत मंत्रों में प्रत्येक अक्षर की विशिष्ट कम्पन आवृत्ति (vibration frequency) होती है। गलत उच्चारण से मंत्र का प्रभाव कम हो सकता है या विपरीत फल मिल सकता है। उदाहरण: "ॐ" का उच्चारण अ+उ+म तीन ध्वनियों से बनता है। "ह्रीं" में ह+र+ई+म चार ध्वनियाँ हैं। गुरु से सीखना सर्वोत्तम है, अन्यथा विश्वसनीय ऑडियो सुनकर अभ्यास करें। Sanskrit mantras have specific vibration frequencies for each syllable. Incorrect pronunciation can reduce effectiveness or produce adverse results. Example: "Om" consists of A+U+M sounds. "Hreem" has H+R+EE+M. Learning from a guru is best; otherwise practice with trusted audio recordings.', 'mantras', 'hi', 'intermediate', '["Panini Ashtadhyayi", "Mantra Shastra", "Tantra Sara"]'),
('108 की संख्या का क्या महत्व है? Why is the number 108 significant?', '108 हिन्दू धर्म में पवित्र संख्या है। सूर्य की पृथ्वी से दूरी सूर्य के व्यास की 108 गुना है। चन्द्रमा की दूरी उसके व्यास की 108 गुना है। संस्कृत वर्णमाला में 54 अक्षर हैं × 2 (शक्ति+शिव) = 108। 12 राशियाँ × 9 ग्रह = 108। 27 नक्षत्र × 4 पाद = 108। इसलिए माला में 108 मणियाँ और 108 बार जाप का विधान है। 108 is sacred in Hinduism. Sun''s distance from Earth is 108× its diameter. Moon''s distance is 108× its diameter. Sanskrit alphabet: 54 letters × 2 (Shakti+Shiva) = 108. 12 zodiac signs × 9 planets = 108. 27 nakshatras × 4 padas = 108. Hence 108 beads in mala and 108 repetitions of mantras.', 'mantras', 'hi', 'intermediate', '["Surya Siddhanta", "Vedic Mathematics", "Jyotish Shastra"]'),
('मंत्र जाप के कितने प्रकार हैं? What are the types of mantra chanting?', 'मंत्र जाप के तीन प्रकार हैं — वाचिक (बोलकर, सबसे कम प्रभावी), उपांशु (होंठ हिलाकर बिना आवाज के, मध्यम प्रभावी), और मानसिक (मन में, सर्वाधिक प्रभावी)। लिखित जाप (मंत्र लिखना) भी एक विधि है। अजपा जाप (श्वास के साथ स्वतः होने वाला जाप) सर्वोच्च स्थिति है। Three types of Japa: Vachika (spoken aloud, least effective), Upamshu (lip movement without sound, moderately effective), and Manasika (mental, most effective). Likhit Japa (writing the mantra) is another method. Ajapa Japa (spontaneous chanting with breath) is the highest state.', 'mantras', 'hi', 'intermediate', '["Yoga Sutras of Patanjali", "Japa Yoga by Swami Sivananda"]'),
('बीज मंत्र क्या होते हैं? What are Beej (Seed) Mantras?', 'बीज मंत्र एकाक्षरी या अल्पाक्षरी मंत्र हैं जो विशिष्ट ऊर्जा का केन्द्र होते हैं। प्रमुख बीज मंत्र — ॐ (ब्रह्म), श्रीं (लक्ष्मी/समृद्धि), ह्रीं (माया/शक्ति), क्लीं (कामदेव/आकर्षण), ऐं (सरस्वती/विद्या), दुं (दुर्गा/रक्षा), गं (गणेश/विघ्न नाश), हौं (शिव/विनाश)। ये शक्तिशाली हैं और गुरु से दीक्षा लेकर जपने चाहिए। Beej mantras are single or few-syllable mantras that are concentrated energy centers. Key beej mantras — Om (Brahman), Shreem (Lakshmi/prosperity), Hreem (Maya/Shakti), Kleem (Kamadeva/attraction), Aim (Saraswati/knowledge), Dum (Durga/protection), Gam (Ganesha/obstacle removal), Haum (Shiva/dissolution). They are powerful and ideally should be chanted after guru diksha.', 'mantras', 'hi', 'advanced', '["Tantra Sara", "Mantra Mahodadhi", "Shakta Pramod"]'),
('योग के कितने प्रकार हैं? What are the main types of Yoga?', 'योग के प्रमुख प्रकार — राज योग (पतंजलि, अष्टांग योग — यम, नियम, आसन, प्राणायाम, प्रत्याहार, धारणा, ध्यान, समाधि), कर्म योग (निष्काम कर्म, गीता), भक्ति योग (ईश्वर प्रेम, नारद भक्ति सूत्र), ज्ञान योग (आत्म विचार, अद्वैत वेदांत), हठ योग (शारीरिक अभ्यास, हठ योग प्रदीपिका), कुण्डलिनी योग (चक्र जागरण), मंत्र योग (जप साधना), लय योग (नाद ध्यान)। Main types: Raja Yoga (Patanjali''s 8 limbs), Karma Yoga (selfless action, Gita), Bhakti Yoga (divine love), Jnana Yoga (self-inquiry, Advaita), Hatha Yoga (physical practice), Kundalini Yoga (chakra awakening), Mantra Yoga (chanting), Laya Yoga (sound meditation).', 'meditation', 'hi', 'beginner', '["Yoga Sutras of Patanjali", "Bhagavad Gita", "Hatha Yoga Pradipika"]'),
('प्राणायाम क्या है और कैसे करें? What is Pranayama and how to practice it?', 'प्राणायाम श्वास नियंत्रण की योग विधि है। प्राण = जीवन शक्ति, आयाम = विस्तार। प्रमुख प्राणायाम — अनुलोम-विलोम (नाड़ी शोधन, बारी-बारी नासिका से श्वास), कपालभाति (तीव्र श्वास उच्छ्वास), भ्रामरी (भौंरे की ध्वनि), उज्जायी (कंठ से श्वास), भस्त्रिका (धौंकनी श्वास), शीतली (ठंडी श्वास)। खाली पेट करें, सुबह का समय सर्वोत्तम। Pranayama is yogic breath control. Prana = life force, Ayama = expansion. Key techniques — Anulom-Vilom (alternate nostril breathing), Kapalbhati (rapid exhalation), Bhramari (bee humming), Ujjayi (ocean breath), Bhastrika (bellows breath), Sheetali (cooling breath). Practice on empty stomach, morning is best.', 'meditation', 'hi', 'beginner', '["Hatha Yoga Pradipika", "Yoga Sutras", "Gheranda Samhita"]'),
('सूर्य नमस्कार के 12 चरण कौन से हैं? What are the 12 steps of Surya Namaskar?', 'सूर्य नमस्कार के 12 आसन — 1. प्रणामासन (नमस्कार), 2. हस्तउत्तानासन (हाथ ऊपर), 3. पादहस्तासन (आगे झुकना), 4. अश्व संचालनासन (घुड़सवार), 5. दण्डासन/प्लैंक, 6. अष्टांग नमस्कार (8 अंग भूमि पर), 7. भुजंगासन (कोबरा), 8. अधोमुख श्वानासन (उल्टा V), 9. अश्व संचालनासन, 10. पादहस्तासन, 11. हस्तउत्तानासन, 12. प्रणामासन। प्रत्येक चरण में एक मंत्र बोलें (ॐ मित्राय नमः, ॐ रवये नमः...)। The 12 poses with mantras: Pranamasana, Hasta Uttanasana, Padahastasana, Ashwa Sanchalanasana, Dandasana, Ashtanga Namaskar, Bhujangasana, Adho Mukha Svanasana, then reverse. Each step has a sun mantra.', 'meditation', 'hi', 'beginner', '["Surya Namaskar Vidhi", "Hatha Yoga Pradipika"]'),
('ध्यान (Meditation) कैसे शुरू करें? How to start meditation for beginners?', 'ध्यान शुरू करने के लिए — शांत स्थान चुनें, सुखासन या पद्मासन में बैठें, रीढ़ सीधी रखें। आँखें बंद करें। पहले 5-10 गहरी साँसें लें। फिर श्वास पर ध्यान केन्द्रित करें — नासिका से प्रवेश और निकास पर। मन भटके तो धीरे से श्वास पर लौटें। शुरू में 5 मिनट करें, धीरे-धीरे 20-30 मिनट तक बढ़ाएँ। To start meditation: choose a quiet place, sit in Sukhasana or Padmasana, keep spine straight. Close eyes. Take 5-10 deep breaths first. Focus on breath — entry and exit at nostrils. When mind wanders, gently return to breath. Start with 5 minutes, gradually increase to 20-30 minutes.', 'meditation', 'hi', 'beginner', '["Yoga Sutras of Patanjali", "Vigyan Bhairav Tantra"]'),
('सात चक्र कौन से हैं? What are the seven Chakras?', 'सात चक्र — 1. मूलाधार (Root, गुदा, लाल, पृथ्वी, "लं"), 2. स्वाधिष्ठान (Sacral, नाभि नीचे, नारंगी, जल, "वं"), 3. मणिपुर (Solar Plexus, नाभि, पीला, अग्नि, "रं"), 4. अनाहत (Heart, हृदय, हरा, वायु, "यं"), 5. विशुद्ध (Throat, कंठ, नीला, आकाश, "हं"), 6. आज्ञा (Third Eye, भ्रू मध्य, नील, मन, "ॐ"), 7. सहस्रार (Crown, शीर्ष, बैंगनी/श्वेत, चेतना, शून्य)। The 7 chakras: 1. Muladhara (Root, red, "Lam"), 2. Svadhisthana (Sacral, orange, "Vam"), 3. Manipura (Solar Plexus, yellow, "Ram"), 4. Anahata (Heart, green, "Yam"), 5. Vishuddha (Throat, blue, "Ham"), 6. Ajna (Third Eye, indigo, "Om"), 7. Sahasrara (Crown, violet/white, silence).', 'meditation', 'hi', 'intermediate', '["Sat Chakra Nirupana", "Kundalini Tantra by Swami Satyananda"]');
