
-- Operation 2: Enhance 10 saints with 500+ char bilingual biographies

UPDATE saints SET 
  biography = 'लाहिड़ी महाशय (1828-1895) को योग विज्ञान को आम गृहस्थों तक पहुँचाने का श्रेय जाता है। उनका जन्म बंगाल के घुरनी गाँव में हुआ। वे ब्रिटिश सरकार में लेखाकार थे और साथ ही महान योगी भी। 1861 में उन्हें हिमालय में महावतार बाबाजी ने क्रिया योग की दीक्षा दी। उन्होंने सिद्ध किया कि गृहस्थ जीवन जीते हुए भी व्यक्ति सर्वोच्च आध्यात्मिक उपलब्धि प्राप्त कर सकता है। उनके शिष्यों में श्री युक्तेश्वर गिरि प्रमुख थे। Lahiri Mahasaya (Shyama Charan Lahiri, 1828-1895) was the householder yogi who revived the ancient science of Kriya Yoga for modern times. Born in Ghurni village, Bengal, he worked as an accountant in the British Military Engineering Department while simultaneously reaching the highest states of God-realization. In 1861, he was initiated into Kriya Yoga by the immortal Mahavatar Babaji in the Himalayas near Ranikhet. He proved that the highest spiritual attainments are possible while living as a householder. His chief disciple Sri Yukteswar Giri carried forward his lineage, eventually reaching Paramahansa Yogananda who brought Kriya Yoga to the West.',
  key_teachings = 'Kriya Yoga as the supreme science of God-realization; spiritual life compatible with householder duties; meditation on the inner light and sound; breath control as the key to consciousness; equality of all beings regardless of caste or religion',
  birth_year = 1828,
  death_year = 1895,
  famous_quotes = '["बाहरी तीर्थ का कोई लाभ नहीं जब तक आंतरिक तीर्थ न हो। (External pilgrimage is useless without internal pilgrimage.)", "क्रिया योग से ही मनुष्य ईश्वर को प्राप्त कर सकता है। (Only through Kriya Yoga can one attain God.)", "गृहस्थ जीवन में रहकर भी मुक्ति संभव है। (Liberation is possible even while living as a householder.)", "श्वास ही आत्मा का सेतु है। (Breath is the bridge to the soul.)"]'::jsonb
WHERE id = '863536b6-bded-4f43-b229-70712576910a';

UPDATE saints SET 
  biography = 'निसर्गदत्त महाराज (1897-1981) महाराष्ट्र के मुंबई में बीड़ी बेचने वाले एक साधारण दुकानदार थे जो अद्वैत वेदांत के सबसे प्रभावशाली आधुनिक गुरुओं में से एक बने। उनका जन्म मराठी ब्राह्मण परिवार में मरुति शिवरामपंत कांभली के रूप में हुआ। 1933 में उन्हें अपने गुरु श्री सिद्धरामेश्वर महाराज से नवनाथ सम्प्रदाय की दीक्षा मिली। उनकी पुस्तक "I Am That" विश्व भर में आत्म-ज्ञान के अन्वेषकों की सर्वप्रिय पुस्तक बनी। Nisargadatta Maharaj (1897-1981) was a humble bidi (hand-rolled cigarette) seller in Mumbai who became one of the most influential Advaita Vedanta teachers of the 20th century. Born Maruti Shivrampant Kambli in a Marathi Brahmin family, he was initiated into the Navnath Sampradaya by his guru Sri Siddharameshwar Maharaj in 1933. His guru instructed him to focus on the sense of "I Am" — and within 3 years he attained Self-realization. His seminal work "I Am That" (a collection of dialogues) has been translated into numerous languages and remains the most recommended book on non-dual consciousness.',
  key_teachings = 'Focus on the pure sense "I Am" before any thought; the witness is beyond the witnessed; you are not the body-mind complex; prior to consciousness is your true nature; understanding is all, practice follows naturally',
  birth_year = 1897,
  death_year = 1981,
  famous_quotes = '["मैं वह हूँ जो मैं हूँ, और यही पर्याप्त है। (I am That I am, and that is enough.)", "ज्ञान स्वयं ही अंतिम उपाय है। (Understanding itself is the ultimate remedy.)", "आप वह नहीं हैं जो आप सोचते हैं कि आप हैं। (You are not what you think you are.)", "जो कुछ भी प्रकट होता है वह वास्तविक नहीं है। (Whatever appears is not real.)"]'::jsonb
WHERE id = 'b68b9aa9-e704-4c3d-a749-81e5c8de5b93';

UPDATE saints SET 
  biography = 'समर्थ रामदास (1608-1681) महाराष्ट्र के महान संत, कवि, दार्शनिक और छत्रपति शिवाजी महाराज के आध्यात्मिक गुरु थे। उनका जन्म जांब गाँव, औरंगाबाद में सूर्याजीपंत ठोसर के घर हुआ। बचपन में ही उन्होंने 12 वर्ष तक राम नाम का जप और तपस्या की। उनकी रचना "दासबोध" मराठी साहित्य का सर्वोत्कृष्ट ग्रंथ माना जाता है जिसमें 20 दशकों में आध्यात्मिक, सामाजिक और व्यावहारिक ज्ञान समाहित है। Samarth Ramdas (1608-1681) was a great Maharashtrian saint, poet, philosopher, and spiritual guru of Chhatrapati Shivaji Maharaj. Born Narayan Suryaji Thosar in Jamb village near Aurangabad, he undertook 12 years of intense tapas chanting Ram Naam at Takli near Nashik. He established 11 Maruti (Hanuman) temples across Maharashtra to inspire strength and devotion. His magnum opus "Dasbodh" (20 dashaks with 200 chapters) is considered the greatest work of Marathi spiritual literature, covering spirituality, social reform, leadership, and practical wisdom. His "Manache Shlok" (verses addressed to the mind) remain widely recited.',
  key_teachings = 'Devotion to Lord Rama and Hanuman; strength through spirituality; Dasbodh as guide to complete living; self-discipline and service to nation; blend of bhakti and karma yoga',
  birth_year = 1608,
  death_year = 1681,
  famous_quotes = '["मना सज्जना भक्तिपंथेचि जावे। (O noble mind, walk the path of devotion.)", "जय जय रघुवीर समर्थ! (Victory to Lord Rama!)", "विवेक म्हणजे सारासार विचार। (Viveka means discerning the real from the unreal.)", "सामर्थ्य आहे चळवळीचे, जो जो करील तयाचे। (Power belongs to those who act.)"]'::jsonb
WHERE id = '40bed9f1-433c-4372-ad56-fe9c2f16c255';

UPDATE saints SET 
  biography = 'परमहंस योगानन्द (1893-1952) भारत के महान योगी और आध्यात्मिक गुरु थे जिन्होंने क्रिया योग और ध्यान की शिक्षाओं को पश्चिमी विश्व में फैलाया। उनका जन्म गोरखपुर, उत्तर प्रदेश में मुकुंद लाल घोष के रूप में हुआ। 1920 में वे अमेरिका गए और 1920 में ही Self-Realization Fellowship की स्थापना की। उनकी आत्मकथा "Autobiography of a Yogi" (1946) विश्व की सर्वाधिक पठित आध्यात्मिक पुस्तकों में से एक है जिसने स्टीव जॉब्स सहित करोड़ों लोगों को प्रभावित किया। Paramahansa Yogananda (1893-1952) was the Indian yogi and guru who introduced millions of Westerners to the teachings of meditation and Kriya Yoga through his organization Self-Realization Fellowship (founded 1920) and his landmark book "Autobiography of a Yogi" (1946). Born Mukunda Lal Ghosh in Gorakhpur, UP, he was a disciple of Sri Yukteswar Giri (in the lineage of Lahiri Mahasaya and Mahavatar Babaji). He spent 32 years in America, lecturing to capacity crowds and establishing meditation centers. His body showed no signs of decay for 20 days after his death — a phenomenon noted by the Los Angeles mortuary director.',
  key_teachings = 'Kriya Yoga meditation technique; direct personal experience of God; harmony of Eastern and Western spiritual traditions; scientific approach to spirituality; energization exercises for body-mind harmony',
  birth_year = 1893,
  death_year = 1952,
  famous_quotes = '["ईश्वर से वार्तालाप में ही सच्ची प्रार्थना है। (True prayer is conversation with God.)", "अपनी इच्छाशक्ति को इतना बलवान बनाओ कि वह ईश्वर तक पहुँचे। (Make your will so strong that it reaches God.)", "मुस्कुराहट आत्मा की भाषा है। (A smile is the language of the soul.)", "सफलता का रहस्य ध्यान केन्द्रित करने में है। (The secret of success lies in concentration.)"]'::jsonb
WHERE id = 'd620f3a4-cb0c-4d1f-8441-19d2272162c8';

UPDATE saints SET 
  biography = 'चैतन्य महाप्रभु (1486-1534) भक्ति आंदोलन के सबसे प्रभावशाली संतों में से एक थे जिन्होंने संकीर्तन (सामूहिक भजन) आंदोलन को बंगाल से पूरे भारत में फैलाया। उनका जन्म नवद्वीप, बंगाल में विश्वंभर मिश्र के रूप में हुआ। 24 वर्ष की आयु में उन्होंने संन्यास लिया। उन्हें कृष्ण का अवतार माना जाता है जो राधा और कृष्ण दोनों के प्रेम को एक साथ अनुभव करने आए। उनके अनुयायियों ने गौड़ीय वैष्णव सम्प्रदाय की स्थापना की जो आज ISKCON (हरे कृष्ण आंदोलन) के रूप में विश्वव्यापी है। Chaitanya Mahaprabhu (1486-1534) was the most influential saint of the Bhakti movement who revolutionized devotional Hinduism through the Sankirtan movement (congregational chanting of God''s names). Born Vishvambhar Mishra in Navadvip, Bengal, he was a brilliant scholar who renounced at age 24. He is considered an avatar of Krishna who came to experience the combined love of Radha and Krishna. His followers established the Gaudiya Vaishnava tradition, now a global movement through ISKCON (International Society for Krishna Consciousness). His philosophy of Achintya Bheda Abheda (inconceivable oneness and difference) reconciles dualism and monism.',
  key_teachings = 'Sankirtan (congregational chanting) as the easiest path to God; Achintya Bheda Abheda philosophy; Hare Krishna Mahamantra as supreme prayer; divine love (prema) as the highest goal; equality of all beings in devotion',
  birth_year = 1486,
  death_year = 1534,
  famous_quotes = '["हरे कृष्ण हरे कृष्ण, कृष्ण कृष्ण हरे हरे। (Hare Krishna Hare Krishna, Krishna Krishna Hare Hare.)", "तृणाद् अपि सुनीचेन, तरोरिव सहिष्णुना। (Be humbler than a blade of grass, more tolerant than a tree.)", "नाम्नाम् अकारि बहुधा निज सर्व शक्तिः। (God has invested all His powers in His holy names.)", "प्रेम ही ईश्वर प्राप्ति का एकमात्र मार्ग है। (Love is the only path to God.)"]'::jsonb
WHERE id = '9980a481-d055-4dbd-a878-30de98acd2f7';

UPDATE saints SET 
  biography = 'श्री अरबिंदो (1872-1950) भारत के महान दार्शनिक, योगी, कवि और स्वतंत्रता सेनानी थे। उनका जन्म कलकत्ता में अरबिंदो घोष के रूप में हुआ। उन्होंने कैम्ब्रिज विश्वविद्यालय से शिक्षा प्राप्त की। प्रारंभ में वे क्रांतिकारी स्वतंत्रता आंदोलन के नेता थे, अलीपुर बम कांड में गिरफ्तार हुए और जेल में उन्हें गहन आध्यात्मिक अनुभव हुआ। 1910 में वे पांडिचेरी चले गए जहाँ उन्होंने "इंटीग्रल योग" (पूर्ण योग) की स्थापना की। उनकी रचना "The Life Divine" और महाकाव्य "Savitri" विश्व साहित्य की अमर कृतियाँ हैं। Sri Aurobindo (1872-1950) was an Indian philosopher, yogi, poet, and freedom fighter. Born Aurobindo Ghose in Kolkata, educated at Cambridge University, he was initially a revolutionary leader in India''s independence movement. Arrested in the Alipore Bomb Case (1908), he experienced profound spiritual transformation in prison. In 1910, he moved to Pondicherry where he developed Integral Yoga — a synthesis that aims at the transformation of the entire human nature by the supramental consciousness. His philosophical works "The Life Divine" and the epic poem "Savitri" (24,000 lines) are masterpieces. With Mirra Alfassa (The Mother), he founded the Sri Aurobindo Ashram and inspired Auroville, the international township.',
  key_teachings = 'Integral Yoga for complete transformation; evolution of consciousness towards the Supermind; spiritual transformation of matter; synthesis of yoga paths; vision of a divine life on earth',
  birth_year = 1872,
  death_year = 1950,
  famous_quotes = '["पूर्णता के लिए आत्म-परिवर्तन आवश्यक है। (Self-transformation is necessary for perfection.)", "भविष्य मानव जाति का अतिमानसिक चेतना में उत्थान है। (The future is the ascent of humanity to supramental consciousness.)", "सारी जिंदगी योग है। (All life is Yoga.)", "ईश्वर प्रत्येक अणु में निवास करता है। (God dwells in every atom.)"]'::jsonb
WHERE id = 'b5aa6cad-14d9-4e99-ab04-ec4763826239';

UPDATE saints SET 
  biography = 'आदि शंकराचार्य (788-820 ई.) भारत के सबसे महान दार्शनिक और अद्वैत वेदांत के प्रवर्तक थे। केरल के कालडी में जन्मे, मात्र 8 वर्ष की आयु में संन्यास लिया और 16 वर्ष की आयु तक सभी प्रमुख ग्रंथों पर भाष्य लिख दिए। उन्होंने मात्र 32 वर्ष के जीवनकाल में पूरे भारत की यात्रा की और चार दिशाओं में चार मठों की स्थापना की — बद्रिकाश्रम (उत्तर), श्रृंगेरी (दक्षिण), द्वारका (पश्चिम), पुरी (पूर्व)। Adi Shankaracharya (788-820 CE) was India''s greatest philosopher and the propounder of Advaita Vedanta (non-dualistic philosophy). Born in Kaladi, Kerala, he took sannyasa at age 8 and by 16 had written commentaries on all major scriptures. In his short life of 32 years, he traveled the entire Indian subcontinent on foot, defeating scholars in philosophical debates and establishing four Mathas (monasteries) in four directions — Badrinath (North), Sringeri (South), Dwarka (West), Puri (East). His works include Vivekachudamani, Bhaja Govindam, Atma Bodha, and commentaries on the Brahma Sutras, Upanishads, and Bhagavad Gita. He is credited with unifying Hinduism and establishing the Dashanami Sannyasa order.',
  key_teachings = 'Advaita Vedanta - Brahman alone is real, the world is an illusion (Maya), the individual self (Atman) is identical with Brahman; Neti Neti (not this, not this) method of inquiry; Shanmata system unifying six Hindu traditions',
  birth_year = 788,
  death_year = 820,
  famous_quotes = '["ब्रह्म सत्यं जगन्मिथ्या, जीवो ब्रह्मैव नापरः। (Brahman is real, the world is illusion, the soul is Brahman alone.)", "भज गोविन्दं भज गोविन्दं, गोविन्दं भज मूढ़मते। (Worship Govinda, O fool!)", "आत्मा ही ब्रह्म है। (The Self is Brahman.)", "चिदानन्दरूपः शिवोऽहम् शिवोऽहम्। (I am Shiva, the form of consciousness and bliss.)"]'::jsonb
WHERE id = '50679c71-5dc4-4b56-a92d-936c66733011';

UPDATE saints SET 
  biography = 'स्वामी शिवानन्द (1887-1963) आधुनिक भारत के सर्वाधिक प्रभावशाली योग गुरुओं में से एक थे। तमिलनाडु के पट्टामडै में जन्मे, उन्होंने चिकित्सा की पढ़ाई की और मलेशिया में डॉक्टर के रूप में सेवा की। 1924 में ऋषिकेश आकर संन्यास लिया और 1936 में Divine Life Society की स्थापना की। उन्होंने 200 से अधिक पुस्तकें लिखीं जो योग, वेदांत, भक्ति और स्वास्थ्य पर हैं। उनके शिष्यों में स्वामी चिदानन्द, स्वामी सच्चिदानन्द, और स्वामी विष्णुदेवानन्द प्रमुख हैं जिन्होंने योग को विश्वव्यापी बनाया। Swami Sivananda (1887-1963) was one of the most influential yoga masters of modern India. Born Kuppuswami in Pattamadai, Tamil Nadu, he studied medicine and served as a doctor in Malaysia before renouncing in 1924 at Rishikesh. He founded the Divine Life Society (1936), Yoga-Vedanta Forest Academy (1948), and authored over 200 books on yoga, Vedanta, health, and devotion. His "Serve, Love, Meditate, Realize" became a universal spiritual motto. His disciples — Swami Chidananda, Swami Satchidananda, Swami Vishnudevananda, and Swami Chinmayananda — spread yoga globally, establishing centers worldwide.',
  key_teachings = 'Serve, Love, Meditate, Realize; synthesis of all yoga paths (Jnana, Bhakti, Karma, Raja); health as the foundation of spiritual practice; selfless service (Nishkama Karma); universal religion of love',
  birth_year = 1887,
  death_year = 1963,
  famous_quotes = '["सेवा करो, प्रेम करो, ध्यान करो, आत्मसाक्षात्कार करो। (Serve, Love, Meditate, Realize.)", "एक ग्राम अभ्यास एक टन सिद्धांत से श्रेष्ठ है। (An ounce of practice is worth tons of theory.)", "ईश्वर को प्रत्येक प्राणी में देखो। (See God in every being.)", "जीवन का उद्देश्य ईश्वर-प्राप्ति है। (The purpose of life is God-realization.)"]'::jsonb
WHERE id = '63d4eb21-5106-435e-845f-472b952fbb7b';

UPDATE saints SET 
  biography = 'स्वामी चिन्मयानन्द (1916-1993) आधुनिक भारत के सबसे प्रभावशाली वेदांत शिक्षकों में से एक थे जिन्होंने गीता ज्ञान यज्ञ के माध्यम से लाखों लोगों को वेदांत से परिचित कराया। केरल के एर्नाकुलम में बालकृष्ण मेनन के रूप में जन्मे, वे पहले पत्रकार और स्वतंत्रता सेनानी थे। स्वामी शिवानन्द से संन्यास की दीक्षा लेकर वे स्वामी तपोवनम से वेदांत शिक्षा प्राप्त किए। 1953 में Chinmaya Mission की स्थापना की जो आज 300+ केन्द्रों के साथ विश्वव्यापी है। Swami Chinmayananda (1916-1993) was a towering Vedanta teacher who made the ancient wisdom of Upanishads and Bhagavad Gita accessible to modern Indians and the world. Born Balakrishna Menon in Ernakulam, Kerala, he was first a journalist and freedom fighter. After taking sannyasa under Swami Sivananda and studying Vedanta under Swami Tapovanam, he launched his first Gita Jnana Yajna in 1951 in Pune. He founded Chinmaya Mission (1953), now a global organization with 300+ centers, and the Chinmaya International Foundation. His commentary on the Bhagavad Gita and Upanishads remain bestsellers. He trained thousands of acharyas to continue Vedanta teaching.',
  key_teachings = 'Vedanta for practical daily living; Bhagavad Gita as management guide; BMI (Body-Mind-Intellect) framework for self-understanding; selfless action; youth empowerment through spiritual education',
  birth_year = 1916,
  death_year = 1993,
  famous_quotes = '["आप वह नहीं हैं जो आप सोचते हैं, बल्कि आप वही हैं जो आप सोचते हैं। (You are not what you think you are, but you are what you think.)", "जो जगत को बदलना चाहते हैं उन्हें पहले स्वयं को बदलना होगा। (To change the world, first change yourself.)", "गीता पढ़ो नहीं, जीओ। (Don''t just read the Gita, live it.)", "मन ही बंधन है, मन ही मुक्ति है। (Mind alone is bondage, mind alone is liberation.)"]'::jsonb
WHERE id = 'a2f74e60-08b4-4d59-97d0-1a3fe8b0b38a';

UPDATE saints SET 
  biography = 'शिरडी साईं बाबा (1838-1918) महाराष्ट्र के शिरडी में रहने वाले महान संत थे जिन्होंने हिन्दू-मुस्लिम एकता का संदेश दिया। उनकी जन्म तिथि और माता-पिता अज्ञात हैं। वे 16 वर्ष की आयु में शिरडी आए और एक जर्जर मस्जिद में रहे जिसे उन्होंने "द्वारकामाई" कहा। वे सदैव धूनी (अखंड अग्नि) के पास बैठते और उसकी विभूति (राख) भक्तों को देते। उन्होंने "सबका मालिक एक" (सबका स्वामी एक है) और "श्रद्धा और सबुरी" (विश्वास और धैर्य) का उपदेश दिया। उनकी समाधि पर बना शिरडी मंदिर प्रतिदिन लाखों श्रद्धालुओं को आकर्षित करता है। Shirdi Sai Baba (1838-1918) was a revered Indian saint who lived in Shirdi, Maharashtra and preached the unity of all religions — Hindu and Muslim. His birth date and parentage remain unknown. He arrived in Shirdi around age 16 and lived in a dilapidated mosque he called "Dwarkamai," where he maintained a sacred fire (dhuni) whose vibhuti (ash) he gave as blessing. His core teachings were "Sabka Maalik Ek" (One God governs all) and "Shraddha aur Saburi" (Faith and Patience). He performed numerous miracles — healing the sick, appearing in multiple places simultaneously, and reading devotees'' minds. The Shirdi Sai Baba Temple, built over his samadhi, receives over 25,000 devotees daily and is one of India''s wealthiest temples.',
  key_teachings = 'Sabka Maalik Ek (God is one for all); Shraddha aur Saburi (Faith and Patience); Hindu-Muslim unity; selfless service to the poor; surrender to the Guru',
  birth_year = 1838,
  death_year = 1918,
  famous_quotes = '["सबका मालिक एक। (One God governs all.)", "श्रद्धा और सबुरी — ये दो ही काफी हैं। (Faith and Patience — these two alone are sufficient.)", "मैं अपने भक्तों को कभी नहीं छोड़ता। (I never forsake my devotees.)", "अल्लाह मालिक है। (Allah/God is the Master.)", "जो मेरी शरण में आता है उसे मैं कभी निराश नहीं करता। (Whoever comes to my refuge, I never disappoint.)"]'::jsonb
WHERE id = 'a2f7c983-3c03-410a-bc44-bd97cc6191f4';
